[phases.setup]
nixPkgs = ["...", "libreoffice", "python311", "python311Packages.pip", "poppler_utils", "jdk"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r server/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"
