[phases.setup]
nixPkgs = ["...", "libreoffice", "python311", "python311Packages.pip", "poppler_utils"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r server/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
